Repository Azure-Samples/modern-data-warehouse-dataops, pull requests merged in 2023-01, with the labels that each got.

#574 Fix external source script and correct ReadMe file
  single_tech_samples/synapseanalytics/sample2_synapseserverless/README.md
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
Labels: bug

#591 upload config file for data retention
  single_tech_samples/synapseanalytics/sample2_synapseserverless/infrastructure/modules/storage.bicep
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/config/datalake_config.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_infrastructure.sh
Labels: single-tech: synapse-serverless

#592 ydaponte/580 582 smart ingest with config file
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/config/datalake_config.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/config/datalake_config_template.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/datasets/Ds_NYCTaxi_ADLS2.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/datasets/Ds_NYCTaxi_Config.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/datasets/Ds_NYCTaxi_HTTP.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_Config.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_0_Main.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_2_IngestData.json
Labels: enhancement

#597 ydaponte/593 pipeline correction
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/datasets/Ds_NYCTaxi_ADLS2_Folder.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_0_Main.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_2_IngestData.json
Labels: bug

#599 ydaponte/598 adding new linked service
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_ADLS2_Folder.json
Labels: dependencies

#601 Elena/597 add keyvault
  single_tech_samples/synapseanalytics/sample2_synapseserverless/infrastructure/main.bicep
  single_tech_samples/synapseanalytics/sample2_synapseserverless/infrastructure/modules/keyvault.bicep
  single_tech_samples/synapseanalytics/sample2_synapseserverless/infrastructure/modules/synapse.bicep
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_infrastructure.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_ADLS2.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_Config.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_HTTP.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_KeyVault.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_Synapse_Serverless_db.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_Synapse_Serverless_master.json
Labels: Sample-2, single-tech: synapse-serverless

#603 ydaponte/584 data retention
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/config/datalake_config_template.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_infrastructure.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_synapse_artifacts.sh
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/notebooks/Nb_NYCTaxi_Config_Operations_Library.ipynb
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/notebooks/Nb_NYCTaxi_Convert_Parquet_to_Delta.ipynb
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/notebooks/Nb_NYCTaxi_Run_Data_Retention.ipynb
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/datasets/Ds_NYCTaxi_ADLS2_Year_Folder.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_ADLS2_Folder.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/linkedservices/Ls_NYCTaxi_HTTP.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_0_Main.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_1_Setup.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_2_IngestData.json
  single_tech_samples/synapseanalytics/sample2_synapseserverless/synapseartifacts/workspace/pipelines/Pl_NYCTaxi_Run_Data_Retention.json
Labels: enhancement
