Repository Azure-Samples/modern-data-warehouse-dataops, pull requests merged in 2024-03, with the labels that each got.

#679 Initial bootstrap changes
  single_tech_samples/fabric/fabric_ci_cd/README.md
  single_tech_samples/fabric/fabric_ci_cd/bootstrap.sh
  single_tech_samples/fabric/fabric_ci_cd/devops/foo.yml
  single_tech_samples/fabric/fabric_ci_cd/infra/fabric_capacity.bicep
  single_tech_samples/fabric/fabric_ci_cd/infra/main.bicep
  single_tech_samples/fabric/fabric_ci_cd/infra/params.json
  single_tech_samples/fabric/fabric_ci_cd/infra/params.json-template
  single_tech_samples/fabric/fabric_ci_cd/scripts/foo.sh
  single_tech_samples/fabric/fabric_ci_cd/src/data-pipelines/covid-pipeline-content.json
  single_tech_samples/fabric/fabric_ci_cd/src/notebooks/nb-covid-data.ipynb
  single_tech_samples/fabric/fabric_ci_cd/src/notebooks/nb-fabric-cicd.ipynb
Labels: single-tech: fabric

#681 Adding CD release code and documentation
  single_tech_samples/fabric/fabric_ci_cd/README.md
  single_tech_samples/fabric/fabric_ci_cd/devops/Scripts/run-deployment-pipelines.ps1
  single_tech_samples/fabric/fabric_ci_cd/devops/azdo-fabric-cd-release-with-approvals.yml
  single_tech_samples/fabric/fabric_ci_cd/devops/azdo-fabric-cd-release.yml
  single_tech_samples/fabric/fabric_ci_cd/devops/foo.yml
  single_tech_samples/fabric/fabric_ci_cd/images/azdo_pipeline_execution.png
  single_tech_samples/fabric/fabric_ci_cd/images/dep_pipeline.png
  single_tech_samples/fabric/fabric_ci_cd/images/manual_approval.png
  single_tech_samples/fabric/fabric_ci_cd/images/manual_approval_2.png
  single_tech_samples/fabric/fabric_ci_cd/infra/params.json
Labels: enhancement

#680 [ANUJ] Bootstrap fixed and documentation update
  single_tech_samples/fabric/fabric_ci_cd/README.md
  single_tech_samples/fabric/fabric_ci_cd/bootstrap.sh
  single_tech_samples/fabric/fabric_ci_cd/docs/images/fabric-cicd.drawio
  single_tech_samples/fabric/fabric_ci_cd/infra/main.bicep
  single_tech_samples/fabric/fabric_ci_cd/src/data-pipelines/pl-covid-data-content.json
  single_tech_samples/fabric/fabric_ci_cd/src/notebooks/nb-city-safety.ipynb
  single_tech_samples/fabric/fabric_ci_cd/src/notebooks/nb-covid-data.ipynb
  single_tech_samples/fabric/fabric_ci_cd/src/notebooks/nb-fabric-cicd.ipynb
Labels: single-tech: fabric

#682 [Fabric CI/CD] Adding architecture diagram
  README.md
  single_tech_samples/fabric/fabric_ci_cd/README.md
  single_tech_samples/fabric/fabric_ci_cd/docs/images/fabric-cicd.drawio
  single_tech_samples/fabric/fabric_ci_cd/images/fabric-cicd.drawio
  single_tech_samples/fabric/fabric_ci_cd/images/fabric-cicd.drawio.svg
Labels: documentation

#683 [Fabric CI/CD] - Adding timeout to CD and final documentation changes
  single_tech_samples/fabric/fabric_ci_cd/README.md
  single_tech_samples/fabric/fabric_ci_cd/devops/azdo-fabric-cd-release-with-approvals.yml
Labels: enhancement

#686 Updating architecture diagram
  single_tech_samples/fabric/fabric_ci_cd/bootstrap.sh
  single_tech_samples/fabric/fabric_ci_cd/images/fabric-cicd.drawio
  single_tech_samples/fabric/fabric_ci_cd/images/fabric-cicd.drawio.svg
Labels: documentation

#690 Correct link to scripts
  single_tech_samples/fabric/fabric_ci_cd/devops/azdo-fabric-cd-release-with-approvals.yml
  single_tech_samples/fabric/fabric_ci_cd/devops/azdo-fabric-cd-release.yml
  single_tech_samples/fabric/fabric_ci_cd/devops/devops_scripts/run-deployment-pipelines.ps1
Labels: bug
